# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Roots Tuition
tagline:          'Roots Tuition'
description:      'Exceptional, inclusive tuition and Oxbridge preparation.'
url:              http://hyde.getpoole.com
baseurl:          /

paginate:         5
paginate_path: "/blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
